# Generated by Django 4.2.15 on 2024-08-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_triggers', '0003_rename_config_id_configsignal_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagebrokerqueue',
            old_name='config_id',
            new_name='config',
        ),
        migrations.RenameField(
            model_name='webhook',
            old_name='config_id',
            new_name='config',
        ),
    ]
