# Generated by Django 4.2.15 on 2024-08-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_triggers', '0004_rename_config_id_messagebrokerqueue_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebrokerqueue',
            name='conn_details',
            field=models.JSONField(blank=True, help_text='Connection details for the queue.', null=True, verbose_name='Connection Details'),
        ),
    ]
