# Generated by Django 4.2.15 on 2024-09-01 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_triggers', '0006_alter_config_content_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebrokerqueue',
            name='timeout_secs',
            field=models.FloatField(blank=True, help_text='The number of seconds to wait before the action is killed.', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Timeout (seconds)'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='timeout_secs',
            field=models.FloatField(blank=True, help_text='The number of seconds to wait before the action is killed.', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Timeout (seconds)'),
        ),
    ]
