name: CI Pipeline

on: [push, pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.tox.yml up -d --wait

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        django-version: [32, 42]
        db: [postgres, mysql, sqlite]
        broker: [rabbitmq, kafka]
    env:
      DJANGO_SETTINGS_MODULE: tests.settings
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tests with Tox
        run: |
          tox -e py${{ matrix.python-version }}-django${{ matrix.django-version }}-${{ matrix.db }}-${{ matrix.broker }}

      - name: Shutdown Docker Compose
        run: docker-compose down
