name: Codecov

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.tox.yml up -d --wait

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: make ci-install-deps-global

      - name: Run tests
        env:
          RABBIT_MQ_HOST: localhost
          RABBIT_MQ_PORT: 5680
          KAFKA_CONN_DETAILS: '{"bootstrap.servers": "localhost:9092"}'
          REDIS_PORT: 6380
          AWS_ENDPOINT: http://localhost:4566
        run: |
          make test-cov

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
